### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by Franky1** [martin-ueding/vigilant-crypto-snatch#25]
The `Dockerfile` needs a `requirements.txt` file to build, but i havent't found one in the repo.

**Comment by martin-ueding** [comment]
This is because I now use Python Poetry, but the person who added the Dockerfile created it for the Setuptools way. Likely one has to adapt this for Poetry, but I haven't looked into that.

I am not sure whether it would make sense to install the stable version into the Docker container anyway. Which version do you want to use?

**Comment by martin-ueding** [comment]
I feel that it doesn't really make sense to support Docker from this repository. I'd rather say that one just installs the stable version from PyPI.
